// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEuAQy_5DSMiBjmEd_5t38l0DtkQQka5M',
    appId: '1:953674745364:web:fd692bd24c74c4eb0a4901',
    messagingSenderId: '953674745364',
    projectId: 'flutter-project-54489',
    authDomain: 'flutter-project-54489.firebaseapp.com',
    storageBucket: 'flutter-project-54489.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgjmCuQIviUhiYHCil0nz5vMF3jpQocO4',
    appId: '1:953674745364:android:bf8ac248e4981f800a4901',
    messagingSenderId: '953674745364',
    projectId: 'flutter-project-54489',
    storageBucket: 'flutter-project-54489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFi_690ncsd_FAVdTSdDrGt6GKO_T5vAA',
    appId: '1:953674745364:ios:2a2aac44ed8616fa0a4901',
    messagingSenderId: '953674745364',
    projectId: 'flutter-project-54489',
    storageBucket: 'flutter-project-54489.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFi_690ncsd_FAVdTSdDrGt6GKO_T5vAA',
    appId: '1:953674745364:ios:6780758809a182a20a4901',
    messagingSenderId: '953674745364',
    projectId: 'flutter-project-54489',
    storageBucket: 'flutter-project-54489.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
